 - name: Stop services
   service:
      name: "{{ item }}"
      state: stopped
   with_items:
      - apache
      - nginx
   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

 - name: Stop services
   service:
      name: "{{ item }}"
      state: stopped
   with_items:
      - httpd
      - nginx
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

 - name: Running pre tasks script
   shell: pre_tasks.sh
